chore(deploy): add deployement scripts and fix gemspec
TankerHQ/identity-ruby pull request #21
Opened 2021-06-08 11:53 UTC by JMounier

- [x] Bump dependencies
- [x] Add deploy and test script
- [x] Update .gemspec

2021-06-08 13:56 UTC, tux3 commented on pyproject.toml
> +flake8 = "^3.8.3"
Pas besoin de flake/black/mypy si on ne les run pas, je pense =)

2021-06-08 14:26 UTC, maximerety requested changes
Nitpick: could you fix the `deployement` typo in the commit title + MR title too?

2021-06-08 14:26 UTC, maximerety commented on pyproject.toml
> +tankerci = { version = ">= 2020.12.3123", source = "gitlab" }
Nitpick: maybe start by requiring a more recent version when introducing the requirement? E.g.  `2021.6.3413` which has been picked up initially.

2021-06-09 13:55 UTC, tux3 approved these changes
LGTM!

2021-06-09 15:48 UTC, maximerety approved these changes

2021-06-11 09:05 UTC, merged